title: "Мій сайт"
description: "Сайт на Jekyll"
baseurl: ""
url: ""

exclude:
  - "node_modules"
  - "vendors"
  - "dist"
  - "build"
  - "package.json"
  - "package-lock.json"
  - "yarn.lock"
  - "webpack.config.js"
  - "vite.config.js"
  - "astro.config.mjs"
  - ".astro"
  - ".output"
  - ".vscode"
  - ".idea"
  - ".gitignore"
